Repository chaos-mesh/website, pull requests merged in 2021-06, with the labels that each got.

#69 Wrote a blog on my experience as lfx-mentee
  blog/2021-06-20-lfx-mentorship-enriching-awschaos.md
  static/img/mentorship_blog.jpeg
  static/img/mentorship_blog2.png
  static/img/mentorship_blog3.png
  static/img/mentorship_blog4.png
  static/img/mentroship_blog1.png
Labels: contribution, docs, first-time-contributor, size/M, status/LGT1

#70 add-caas-blog
  blog/2021-06-25-chaos-mesh-remake-one-step-closer-toward-chaos-as-a-service.md
  static/img/chaos-engineering-tools-as-a-service.jpeg
  static/img/chaos-mesh-optimized-architecture.jpeg
  static/img/chaos-mesh-remake-architecture.jpeg
  static/img/chaosd-chaos-engineering-command-line-tool.jpeg
  static/img/closed-loop-of-chaos-engineering.jpeg
Labels: contribution, size/L, status/LGT1

#71 update-mentee-blog
  blog/2021-06-20-lfx-mentorship-enriching-awschaos.md
Labels: contribution, size/S, status/LGT1

#50 Update stress chaos experiment doc with stress-ng option details
  docs/chaos_experiments/stress_chaos.md
Labels: status/LGT1, status/can-merge

#68 docs: fix wrong format in features.md
  docs/overview/features.md
Labels: contribution, docs, first-time-contributor, size/XS, status/LGT1, status/can-merge
