Repository chaos-mesh/website, pull requests merged in 2021-05, with the labels that each got.

#55 Update faqs.md
  blog/2020-10-30-chaos-engineering-breaking-things-intentionally.md
  blog/2020-9-25-chaos-mesh-1.0-chaos-engineering-on-kubernetes-made-easier.md
  blog/2021-02-05-celebrating-one-year-of-chaos-mesh-looking-back-and-ahead.md
  versioned_docs/version-1.2.0/faqs.md
Labels: status/LGT1

#60 DNSChaos on OpenShift permissions issue resolution
  versioned_docs/version-1.2.1/faqs.md
Labels: contribution, size/S, status/LGT1

#64 create quick-start.md
  docs/quick-start.md
Labels: contribution, do-not-merge/blocked-paths, docs, first-time-contributor, size/L, status/LGT1
