Repository chaos-mesh/website, pull requests merged in 2022-07, with the labels that each got.

#317 document: add description for injecting JVM fault into MySQL client
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-jvm-application-chaos-in-physical-nodes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-jvm-application-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/simulate-jvm-application-chaos-in-physical-nodes.md
Labels: documentation, status/LGT1, type/bug-fix, translation/doing, status/can-merge, size/M, type/enhancement, v2.3

#321 Clarify the usage of replace.body
  docs/simulate-http-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-http-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/simulate-http-chaos-on-kubernetes.md
  versioned_docs/version-2.2.0/simulate-http-chaos-on-kubernetes.md
Labels: documentation, status/LGT1, status/can-merge, size/M, type/enhancement

#322 reUpdate description of memory stressors
  docs/simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.2/simulate-heavy-stress-on-kubernetes.md
  versioned_docs/version-2.2.2/simulate-heavy-stress-on-kubernetes.md
Labels: documentation, type/cherry-pick, status/LGT1, size/XS, type/bug-fix, status/can-merge, v2.2

#328 chore: add truncate for blog
  blog/2022-06-07-chaos-mesh-qa-kubecon-eu-2022.md
Labels: status/LGT1, size/XS, status/can-merge
