Repository chaos-mesh/website, pull requests merged in 2022-02, with the labels that each got.

#246 fix: JS float pitfall
  src/components/PickHelmVersion.jsx
Labels: status/LGT1, size/XS, type/bug-fix

#226 chore: add notes for pod-failure chaos
  docs/simulate-pod-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-pod-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-pod-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.3/simulate-pod-chaos-on-kubernetes.md
  versioned_docs/version-2.0.7/simulate-pod-chaos-on-kubernetes.md
  versioned_docs/version-2.1.3/simulate-pod-chaos-on-kubernetes.md
Labels: status/LGT1, status/can-merge, size/M, docs

#248 fix: removed docker registry mirrors tips
  docs/quick-start.md
  i18n/zh/docusaurus-plugin-content-docs/current/quick-start.md
Labels: status/LGT1, contribution, first-time-contributor, status/can-merge, size/S, docs

#251 fix: should be CPU instead of memory
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.3/simulate-heavy-stress-on-kubernetes.md
Labels: documentation, status/LGT1, contribution, first-time-contributor, size/XS, type/bug-fix

#244 document: add network bandwidth and port occupy document for chaosd
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-network-chaos-in-physical-nodes.md
Labels: documentation, status/LGT1, translation/doing, size/L, 2.2

#250 chore: announcing incubation
  docusaurus.config.js
  i18n/zh/docusaurus-plugin-content-docs/current/overview.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/overview.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.3/overview.md
Labels: status/LGT1, size/XS, translation/doing

#242 Update overview.md
  docs/overview.md
Labels: documentation, do-not-merge/blocked-paths, contribution, first-time-contributor, size/XS, translation/doing

#240 Typo in helm chart repo link fix
  versioned_docs/version-2.1.3/production-installation-using-helm.md
Labels: documentation, contribution, first-time-contributor, size/XS

#255 chores: update chaos mesh project status
  src/pages/index.js
  versioned_docs/version-2.0.7/overview.md
  versioned_docs/version-2.1.3/overview.md
Labels: documentation, status/LGT1, size/XS, translation/from-zh, status/can-merge
