Repository chaos-mesh/website, pull requests merged in 2022-04, with the labels that each got.

#270 docs: update testing coverage,
  docs/supported-releases.md
  i18n/zh/docusaurus-plugin-content-docs/current/supported-releases.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.4/supported-releases.md
  versioned_docs/version-2.1.4/supported-releases.md
Labels: documentation, status/LGT1, translation/done, status/can-merge, size/M

#273 add document for stress oom_score_adj
  docs/simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-heavy-stress-on-kubernetes.md
Labels: documentation, status/LGT1, do-not-merge/blocked-paths, size/XS, status/can-merge, v2.2

#275 Update simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.4/simulate-heavy-stress-on-kubernetes.md
  versioned_docs/version-2.0.7/simulate-heavy-stress-on-kubernetes.md
  versioned_docs/version-2.1.4/simulate-heavy-stress-on-kubernetes.md
Labels: documentation, status/LGT1, contribution, first-time-contributor, status/can-merge, size/S

#277 add a description link to the oom_score_adj
  .github/workflows/markdown-link-check.json
  docs/simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-heavy-stress-on-kubernetes.md
Labels: documentation, status/LGT1, do-not-merge/blocked-paths, size/XS, translation/done, status/can-merge
