Repository chaos-mesh/website, pull requests merged in 2022-06, with the labels that each got.

#306 Blog:Chaos Mesh Q&A at KUBECON EU 2022
  blog/2022-06-07-chaos-mesh-qa-kubecon-eu-2022.md
Labels: status/LGT1, contribution, first-time-contributor, status/can-merge, size/M

#307 Update validate-auth to chaos-mesh-validate-auth
  i18n/zh/docusaurus-plugin-content-docs/current/uninstallation.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/uninstallation.md
Labels: documentation, status/LGT1, size/XS, status/can-merge

#305 zh document: update dns example for chaosd
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-network-chaos-in-physical-nodes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/simulate-network-chaos-in-physical-nodes.md
Labels: documentation, status/LGT1, translation/doing, status/can-merge, size/S

#315 document: mv the guide to chaos mesh 2.1 to v2.1.5
  i18n/zh/docusaurus-plugin-content-docs/current/img/quick-start-chaos-mesh-dashboard.png
  i18n/zh/docusaurus-plugin-content-docs/current/the-guide-to-chaos-mesh-v21.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/img/http-config.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/img/http-detail.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/img/http-exp-meta.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/img/k8s-http-exp.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/img/k8s-network-exp.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/img/network-config.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/img/network-meta.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/img/quick-start-chaos-mesh-dashboard.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/img/suspend-task.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/img/web-show1.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/img/web-show2.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/img/workflow-meta.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/the-guide-to-chaos-mesh-v21.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/img/http-config.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/img/http-detail.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/img/http-exp-meta.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/img/k8s-http-exp.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/img/k8s-network-exp.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/img/network-config.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/img/network-meta.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/img/quick-start-chaos-mesh-dashboard.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/img/suspend-task.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/img/web-show1.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/img/web-show2.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/img/workflow-meta.png
  sidebars.js
  versioned_docs/version-2.1.5/img/quick-start-chaos-mesh-dashboard.png
  versioned_docs/version-2.1.5/img/quick-start-experiment-information.png
  versioned_docs/version-2.1.5/img/quick-start-fill-in-info.png
  versioned_docs/version-2.1.5/img/quick-start-new-experiment-dashboard.png
  versioned_docs/version-2.1.5/img/quick-start-report-error.png
  versioned_docs/version-2.1.5/img/quick-start-select-cpu.png
  versioned_docs/version-2.1.5/img/quick-start-select-experiment-on-dashboard.png
  versioned_docs/version-2.1.5/img/quick-start-select-experiment-type.png
  versioned_docs/version-2.1.5/img/quick-start-select-fault-behavior.png
  versioned_docs/version-2.1.5/img/quick-start-select-request-abort.png
  versioned_docs/version-2.1.5/img/quick-start-stress-test.png
  versioned_docs/version-2.1.5/img/quick-start-test-application-architecture.png
  versioned_docs/version-2.1.5/img/quick-start-two-pods-for-sql-queries.png
  versioned_docs/version-2.1.5/img/quick-start-write-address.png
  versioned_docs/version-2.1.5/the-guide-to-chaos-mesh-v21.md
  versioned_docs/version-2.2.0/img/quick-start-experiment-information.png
  versioned_docs/version-2.2.0/img/quick-start-fill-in-info.png
  versioned_docs/version-2.2.0/img/quick-start-new-experiment-dashboard.png
  versioned_docs/version-2.2.0/img/quick-start-report-error.png
  versioned_docs/version-2.2.0/img/quick-start-select-cpu.png
  versioned_docs/version-2.2.0/img/quick-start-select-experiment-on-dashboard.png
  versioned_docs/version-2.2.0/img/quick-start-select-experiment-type.png
  versioned_docs/version-2.2.0/img/quick-start-select-fault-behavior.png
  versioned_docs/version-2.2.0/img/quick-start-select-request-abort.png
  versioned_docs/version-2.2.0/img/quick-start-stress-test.png
  versioned_docs/version-2.2.0/img/quick-start-test-application-architecture.png
  versioned_docs/version-2.2.0/img/quick-start-two-pods-for-sql-queries.png
  versioned_docs/version-2.2.0/img/quick-start-write-address.png
  versioned_docs/version-2.2.0/the-guide-to-chaos-mesh-v21.md
  versioned_sidebars/version-2.1.5-sidebars.json
  versioned_sidebars/version-2.2.0-sidebars.json
Labels: documentation, status/LGT1, size/XXL, status/can-merge

#309 Add docs to introduce Chaos Mesh Release Cycle
  docs/release-2.3-tracking.md
  docs/release-cycle.md
  sidebars.js
Labels: documentation, status/LGT1, status/can-merge, size/L

#313 configure the develop environment
  docs/configure-development-environment.md
Labels: documentation, status/LGT1, status/can-merge, size/L

#316 Fix the note format in upgrade-from-2.1-to-2.2.md
  docs/upgrade-from-2.1-to-2.2.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/upgrade-from-2.1-to-2.2.md
  versioned_docs/version-2.2.0/upgrade-from-2.1-to-2.2.md
Labels: documentation, status/LGT1, type/bug-fix, translation/done, status/can-merge, size/S

#318 fix: correct IOChaos containerNames
  versioned_docs/version-2.2.0/simulate-io-chaos-on-kubernetes.md
Labels: documentation, status/LGT1, do-not-merge/blocked-paths, contribution, first-time-contributor, size/XS
