Repository chaos-mesh/website, pull requests merged in 2022-12, with the labels that each got.

#367 v2.5: add remote-cluster-management doc
  sidebars.js
  versioned_docs/version-2.5.0/remote-cluster-management.md
  versioned_sidebars/version-2.5.0-sidebars.json
Labels: documentation, do-not-merge/blocked-paths, size/M

#368 Update basic-features.md
  versioned_docs/version-2.5.0/basic-features.md
Labels: documentation, status/LGT1, contribution, first-time-contributor, size/XS, status/can-merge

#369 update leaderElection doc
  docs/production-installation-using-helm.md
  i18n/zh/docusaurus-plugin-content-docs/current/production-installation-using-helm.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.3/production-installation-using-helm.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.3.3/production-installation-using-helm.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/production-installation-using-helm.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/production-installation-using-helm.md
  versioned_docs/version-2.2.3/production-installation-using-helm.md
  versioned_docs/version-2.3.3/production-installation-using-helm.md
  versioned_docs/version-2.4.3/production-installation-using-helm.md
  versioned_docs/version-2.5.0/production-installation-using-helm.md
Labels: documentation, size/S
