Repository chaos-mesh/website, pull requests merged in 2022-09, with the labels that each got.

#344 Fix typo in workflow documentation
  docs/create-chaos-mesh-workflow.md
Labels: documentation, status/LGT1, do-not-merge/blocked-paths, contribution, first-time-contributor, size/XS

#342 Fix docs mistypes in configure-enabled-namespace section
  docs/configure-enabled-namespace.md
  versioned_docs/version-2.0.7/configure-enabled-namespace.md
  versioned_docs/version-2.1.7/configure-enabled-namespace.md
  versioned_docs/version-2.2.3/configure-enabled-namespace.md
  versioned_docs/version-2.3.0/configure-enabled-namespace.md
Labels: documentation, status/LGT1, contribution, first-time-contributor, status/can-merge, size/S

#346 fix broken links
  blog/2020-01-15-chaos-mesh-your-chaos-engineering-solution.md
  blog/2020-04-20-simulating-clock-skew-in-k8s-without-affecting-other-containers-on-node.md
  blog/2021-06-25-chaos-mesh-remake-one-step-closer-toward-chaos-as-a-service.md
Labels: status/LGT1, size/XS

#345 Release Tracking for 2.4
  docs/release-2.3-tracking.md
  docs/release-2.4-tracking.md
  sidebars.js
Labels: documentation, status/LGT1, status/can-merge, size/M

#329 add documents for blockchaos in latest and 2.3.0
  docs/simulate-block-chaos-on-kubernetes.md
  sidebars.js
  versioned_docs/version-2.3.1/simulate-block-chaos-on-kubernetes.md
  versioned_sidebars/version-2.3.1-sidebars.json
Labels: documentation, status/LGT1, status/can-merge, size/L, v2.3

#350 Correct namespace in Quick Start
  docs/common/verify-installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/common/verify-installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.3.1/common/verify-installation.md
  versioned_docs/version-2.3.1/common/verify-installation.md
Labels: documentation, status/LGT1, contribution, first-time-contributor, require-LGT1, status/can-merge, size/S

#356 chore: remove katacoda
  docusaurus.config.js
  i18n/zh/docusaurus-theme-classic/navbar.json
  src/pages/interactive-tutorial.js
Labels: size/M
