Repository chaos-mesh/website, pull requests merged in 2022-08, with the labels that each got.

#331 chore: update supported releases
  docs/supported-releases.md
  i18n/zh/docusaurus-plugin-content-docs/current/supported-releases.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.3.0/supported-releases.md
  versioned_docs/version-2.3.0/supported-releases.md
Labels: documentation, status/LGT1, do-not-merge/blocked-paths, size/S, v2.3

#338 add --remote-name flag when downloading chaosctl
  docs/chaosctl-tool.md
  i18n/zh/docusaurus-plugin-content-docs/current/chaosctl-tool.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.3.0/chaosctl-tool.md
  versioned_docs/version-2.3.0/chaosctl-tool.md
Labels: documentation, status/LGT1, size/XS, type/bug-fix, status/can-merge

#320 Add docs of Redis chaos
  docs/simulate-redis-chaos-on-physical-nodes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-redis-chaos-on-physical-nodes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.3.0/simulate-redis-chaos-on-physical-nodes.md
  sidebars.js
  versioned_docs/version-2.3.0/simulate-redis-chaos-on-physical-nodes.md
Labels: documentation, status/LGT1, translation/done, size/XXL, status/can-merge, type/enhancement, v2.3

#339 Clarify purpose of safe mode
  docs/production-installation-using-helm.md
Labels: documentation, status/LGT1, do-not-merge/blocked-paths, contribution, first-time-contributor, size/XS, translation/doing

#337 the default value of startingDeadlineSeconds is not 0, is nil
  docs/define-scheduling-rules.md
  i18n/zh/docusaurus-plugin-content-docs/current/define-scheduling-rules.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.3.0/define-scheduling-rules.md
  versioned_docs/version-2.3.0/define-scheduling-rules.md
Labels: documentation, status/LGT1, type/bug-fix, status/can-merge, size/S

#324 [Fix] modify developer guide doc
  docs/add-new-chaos-experiment-type.md
  docs/extend-chaos-daemon-interface.md
  i18n/zh/docusaurus-plugin-content-docs/current/add-new-chaos-experiment-type.md
  i18n/zh/docusaurus-plugin-content-docs/current/extend-chaos-daemon-interface.md
Labels: documentation, status/LGT1, contribution, first-time-contributor, size/XL, status/can-merge

#340 Fix misspelling of chaosd
  docs/define-chaos-experiment-scope.md
  docs/simulate-physical-machine-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-physical-machine-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.2.3/simulate-physical-machine-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.3.0/simulate-physical-machine-chaos.md
  versioned_docs/version-2.2.3/define-chaos-experiment-scope.md
  versioned_docs/version-2.2.3/simulate-physical-machine-chaos.md
  versioned_docs/version-2.3.0/define-chaos-experiment-scope.md
  versioned_docs/version-2.3.0/simulate-physical-machine-chaos.md
Labels: documentation, status/LGT1, contribution, first-time-contributor, status/can-merge, size/S
