Repository chaos-mesh/website, pull requests merged in 2022-03, with the labels that each got.

#257 fix: update start:default commands
  docs/configure-development-environment.md
  i18n/zh/docusaurus-plugin-content-docs/current/configure-development-environment.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.3/configure-development-environment.md
  versioned_docs/version-2.1.3/configure-development-environment.md
Labels: documentation, status/LGT1, do-not-merge/blocked-paths, size/XS, translation/no-need

#239 Update docs of StressChaos
  docs/simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.3/simulate-heavy-stress-on-kubernetes.md
  versioned_docs/version-2.0.7/simulate-heavy-stress-on-kubernetes.md
  versioned_docs/version-2.1.3/simulate-heavy-stress-on-kubernetes.md
Labels: documentation, status/LGT1, translation/done, status/can-merge, size/M

#258 chore: update screenshot for choose-task-type
  i18n/zh/docusaurus-plugin-content-docs/current/create-chaos-mesh-workflow.md
  i18n/zh/docusaurus-plugin-content-docs/current/img/choose-task-type.png
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.3/create-chaos-mesh-workflow.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.3/img/choose-task-type.png
Labels: documentation, status/LGT1, size/XS, translation/no-need

#252 Add document `chaosctl-tool` to sidebar
  sidebars.js
  versioned_sidebars/version-2.0.7-sidebars.json
  versioned_sidebars/version-2.1.3-sidebars.json
Labels: documentation, status/LGT1, size/XS, translation/no-need

#263 Add new adopter logo: Maycur
  src/data/whoIsUsing.js
  static/img/logos/maycur.png
Labels: status/LGT1, size/XS

#262 add doc for recover-cmd
  docs/simulate-process-chaos-in-physical-nodes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-process-chaos-in-physical-nodes.md
Labels: documentation, status/LGT1, translation/doing, status/can-merge, size/S, v2.2

#264 Docs: add coding guidelines
  docs/developer-guide-overview.md
  i18n/zh/docusaurus-plugin-content-docs/current/developer-guide-overview.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.3/developer-guide-overview.md
  versioned_docs/version-2.1.3/developer-guide-overview.md
Labels: documentation, status/LGT1, status/can-merge, size/S

#265 document: fix link
  versioned_docs/version-0.9.1/user_guides/iochaos.md
Labels: documentation, status/LGT1, size/XS, status/can-merge

#256 ZH document: 10 Minute Guide to Chaos Mesh v2.1.0
  i18n/zh/docusaurus-plugin-content-docs/current/img/http-config.png
  i18n/zh/docusaurus-plugin-content-docs/current/img/http-detail.png
  i18n/zh/docusaurus-plugin-content-docs/current/img/http-exp-meta.png
  i18n/zh/docusaurus-plugin-content-docs/current/img/k8s-http-exp.png
  i18n/zh/docusaurus-plugin-content-docs/current/img/k8s-network-exp.png
  i18n/zh/docusaurus-plugin-content-docs/current/img/network-config.png
  i18n/zh/docusaurus-plugin-content-docs/current/img/network-meta.png
  i18n/zh/docusaurus-plugin-content-docs/current/img/quick-start-chaos-mesh-dashboard.png
  i18n/zh/docusaurus-plugin-content-docs/current/img/suspend-task.png
  i18n/zh/docusaurus-plugin-content-docs/current/img/web-show1.png
  i18n/zh/docusaurus-plugin-content-docs/current/img/web-show2.png
  i18n/zh/docusaurus-plugin-content-docs/current/img/workflow-meta.png
  i18n/zh/docusaurus-plugin-content-docs/current/the-guide-to-chaos-mesh-v21.md
  sidebars.js
Labels: documentation, status/LGT1, translation/doing, status/can-merge, size/L, requires-followup

#253 document: inject fault into MySQL java client by chaosd
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-jvm-application-chaos-in-physical-nodes.md
Labels: documentation, status/LGT1, translation/doing, status/can-merge, size/L, v2.2
