Repository chaos-mesh/website, pull requests merged in 2022-05, with the labels that each got.

#288 Update the description of MemoryStrossors size in simulate-heavy-stress-on-kubernetes.md
  docs/simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-heavy-stress-on-kubernetes.md
Labels: documentation, status/LGT1, size/XS, translation/done, status/can-merge

#286 update the version map between Chaosd and Chaos Mesh
  blog/2021-06-25-chaos-mesh-remake-one-step-closer-toward-chaos-as-a-service.md
  docs/simulate-physical-machine-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-network-chaos-in-physical-nodes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-physical-machine-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-network-chaos-in-physical-nodes.md
Labels: documentation, translation/doing, status/can-merge, size/M, status/LGT2, requires-followup

#282 Update validate-auth to chaos-mesh-validate-auth
  docs/uninstallation.md
Labels: documentation, status/LGT1, contribution, size/XS, translation/doing, status/PTAL, status/can-merge, requires-followup

#285 chaosd: add a doc to introduce how to pause the program on service mode
  docs/simulate-process-chaos-in-physical-nodes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-process-chaos-in-physical-nodes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-process-chaos-in-physical-nodes.md
  versioned_docs/version-2.1.5/simulate-process-chaos-in-physical-nodes.md
Labels: documentation, status/LGT1, contribution, first-time-contributor, translation/done, status/can-merge, size/M

#280 docs: update usage restriction for podchaos
  docs/simulate-pod-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-pod-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-pod-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-pod-chaos-on-kubernetes.md
  versioned_docs/version-2.0.7/simulate-pod-chaos-on-kubernetes.md
  versioned_docs/version-2.1.5/simulate-pod-chaos-on-kubernetes.md
Labels: documentation, status/LGT1, translation/done, status/PTAL, status/can-merge, size/S

#293 Remove Vector WASM Transform link
  blog/2021-06-25-chaos-mesh-remake-one-step-closer-toward-chaos-as-a-service.md
Labels: status/LGT1, size/XS, type/bug-fix, status/can-merge

#292 document: simulate file fault in physical machine by using chaosd
  docs/simulate-file-chaos-in-physical-nodes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-file-chaos-in-physical-nodes.md
  sidebars.js
Labels: documentation, status/LGT1, size/XL, status/can-merge

#291 Update the English document of simulating network fault into physical machine by using chaosd
  docs/simulate-network-chaos-in-physical-nodes.md
Labels: documentation, status/LGT1, size/XL, status/can-merge

#267 Add for persistence Chaos Dashboard
  docs/persistence-dashboard.md
  docs/production-installation-using-helm.md
  docs/simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/persistence-dashboard.md
  i18n/zh/docusaurus-plugin-content-docs/current/production-installation-using-helm.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-heavy-stress-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/persistence-dashboard.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/production-installation-using-helm.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-heavy-stress-on-kubernetes.md
  sidebars.js
  versioned_docs/version-2.0.7/simulate-heavy-stress-on-kubernetes.md
  versioned_docs/version-2.1.5/persistence-dashboard.md
  versioned_docs/version-2.1.5/production-installation-using-helm.md
  versioned_docs/version-2.1.5/simulate-heavy-stress-on-kubernetes.md
  versioned_sidebars/version-2.1.5-sidebars.json
Labels: documentation, status/LGT1, size/XL, translation/done, status/can-merge, v2.2

#298 indicate the changes of HTTPChaos behaviors
  docs/simulate-http-chaos-on-kubernetes.md
Labels: documentation, status/LGT1, translation/doing, status/can-merge, size/M, v2.2

#287 Add docs of AzureChaos
  docs/simulate-aws-chaos.md
  docs/simulate-azure-chaos.md
  docs/simulate-gcp-chaos.md
  docs/simulate-jvm-application-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-aws-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-azure-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-dns-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-gcp-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-kernel-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-physical-machine-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-aws-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-dns-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-gcp-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-kernel-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-aws-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-dns-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-gcp-chaos.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-kernel-chaos-on-kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-physical-machine-chaos.md
  sidebars.js
  versioned_docs/version-1.2.4/chaos_experiments/awschaos.md
  versioned_docs/version-2.0.7/simulate-aws-chaos.md
  versioned_docs/version-2.0.7/simulate-gcp-chaos.md
  versioned_docs/version-2.1.5/simulate-aws-chaos.md
  versioned_docs/version-2.1.5/simulate-gcp-chaos.md
  versioned_docs/version-2.1.5/simulate-jvm-application-chaos.md
Labels: documentation, status/LGT1, size/XL, translation/done, status/can-merge, v2.2

#300 fix: version table display error
  i18n/zh/docusaurus-plugin-content-docs/current/simulate-physical-machine-chaos.md
Labels: documentation, status/LGT1, contribution, first-time-contributor, size/XS, status/can-merge

#302 fix the usage of PickVersion in offline installation
  docs/offline-installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/offline-installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/offline-installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/offline-installation.md
  src/components/PickVersion.jsx
  versioned_docs/version-2.0.7/offline-installation.md
  versioned_docs/version-2.1.5/offline-installation.md
Labels: documentation, status/LGT1, status/can-merge, size/S

#303 docs: upgrade from 2.1 to 2.2
  docs/upgrade-from-2.1-to-2.2.md
  i18n/zh/docusaurus-plugin-content-docs/current/upgrade-from-2.1-to-2.2.md
  sidebars.js
Labels: documentation, status/LGT1, status/can-merge, size/L, v2.2

#299 docs: StatusCheck in Workflow
  docs/create-chaos-mesh-workflow.md
  docs/status-check-in-workflow.md
  i18n/zh/docusaurus-plugin-content-docs/current/create-chaos-mesh-workflow.md
  i18n/zh/docusaurus-plugin-content-docs/current/status-check-in-workflow.md
  sidebars.js
Labels: documentation, status/LGT1, size/XL, status/can-merge, translation/no-need, v2.2
